version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: frontend
    volumes:
      - ./nginx/conf/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    #command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - 80:80

  images:
    container_name: backend
    image: nginx:latest
    expose:
      - 10177
    volumes:
      - ./nginx/images:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    #ports:
    #  - 81:80
